In [1]:
import os
from tqdm.notebook import tqdm,tnrange
from bs4 import BeautifulSoup as bs
from nltk.stem import PorterStemmer,SnowballStemmer,WordNetLemmatizer
from nltk.tokenize import word_tokenize
import nltk
from nltk.corpus import stopwords
import json
import math
import numpy as np
#punkt and stopqwords
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [WinError 10054] An
[nltk_data]     existing connection was forcibly closed by the remote
[nltk_data]     host>
[nltk_data] Error loading stopwords: <urlopen error [WinError 10054]
[nltk_data]     An existing connection was forcibly closed by the
[nltk_data]     remote host>


False

In [2]:
os.chdir('CSE508_Winter2023_Dataset')

In [3]:
# add <?xml version="1.0" encoding="UTF-8"?> to the beginning of each file and save it
# for file in os.listdir():
#     with open(file, 'r+') as f:
#         # store the content of the file in a variable
#         data = f.read()
#         # move cursor to the beginning of the file
#         f.seek(0, 0)
#         # write the xml declaration at the beginning of the file along with data
#         f.write('<?xml version="1.0" encoding="UTF-8"?\n>' + data)
#         f.close()

In [4]:
# files before extracting the title and text tags
# os.chdir('../CSE508_Winter2023_Dataset/')
for file in tqdm(os.listdir()[0:5]):
    with open(file, 'r') as f:
        print(f.read())
        f.close()

<DOC>
<DOCNO>
1
</DOCNO>
<TITLE>
experimental investigation of the aerodynamics of a
wing in a slipstream .
</TITLE>
<AUTHOR>
brenckman,m.
</AUTHOR>
<BIBLIO>
j. ae. scs. 25, 1958, 324.
</BIBLIO>
<TEXT>
  an experimental study of a wing in a propeller slipstream was
made in order to determine the spanwise distribution of the lift
increase due to slipstream at different angles of attack of the wing
and at different free stream to slipstream velocity ratios .  the
results were intended in part as an evaluation basis for different
theoretical treatments of this problem .
  the comparative span loading curves, together with supporting
evidence, showed that a substantial part of the lift increment
produced by the slipstream was due to a /destalling/ or boundary-layer-control
effect .  the integrated remaining lift increment,
after subtracting this destalling lift, was found to agree
well with a potential flow theory .
  an empirical evaluation of the destalling effects was made for
the speci

In [5]:
os.chdir('../CSE508_Winter2023_Dataset_XML')
# for filename in os.listdir():
#     with open(filename, 'r+') as f:
#         content = f.read()
#         soup = bs(content, 'xml')
#         title = soup.find('TITLE').text
#         title = title[1:-1]
#         text = soup.find('TEXT').text
#         text = text[1:-1]
#         f.truncate(0)
#         f.seek(0, 0)
#         f.write(title + ' ' + text)
#         f.close()

# files after extracting the title and text tags
for filename in tqdm(os.listdir()[0:5]):
    with open(filename, 'r') as f:
        print()
        print(filename)
        print(f.read())
        f.close()


cranfield0001
experimental investigation of the aerodynamics of a
wing in a slipstream .   an experimental study of a wing in a propeller slipstream was
made in order to determine the spanwise distribution of the lift
increase due to slipstream at different angles of attack of the wing
and at different free stream to slipstream velocity ratios .  the
results were intended in part as an evaluation basis for different
theoretical treatments of this problem .
  the comparative span loading curves, together with supporting
evidence, showed that a substantial part of the lift increment
produced by the slipstream was due to a /destalling/ or boundary-layer-control
effect .  the integrated remaining lift increment,
after subtracting this destalling lift, was found to agree
well with a potential flow theory .
  an empirical evaluation of the destalling effects was made for
the specific configuration of the experiment .

cranfield0002
simple shear flow past a flat plate in an incompressible fl

In [15]:
def preprocess(filename):
    # open the file and read the text
    with open(filename, 'r') as f:
        text = f.read()
    # Lowercase the text
    text = text.lower()
    # Perform tokenization
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    # remove punctuations but not hyphen separated words
    tokens = [w for w in tokens if w.isalpha() or '-' in w]
    # remove words with numbers
    tokens = [w for w in tokens if not any(c.isdigit() for c in w)]
    # Remove blank space tokens
    tokens = [w for w in tokens if w.strip()]
    # remove single character tokens
    tokens = [w for w in tokens if len(w) > 1]
    return tokens

# create a preprocessing function to preprocess the query that will take a string query as input and return a list of tokens.
# used the previous preprocess function as reference.
def set_preprocess_query(text):
    text = text.lower()
    # Perform tokenization
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    # remove punctuations but not hyphen separated words
    tokens = [w for w in tokens if w.isalpha() or '-' in w]
    # remove words with numbers
    tokens = [w for w in tokens if not any(c.isdigit() for c in w)]
    # Remove blank space tokens
    tokens = [w for w in tokens if w.strip()]
    # remove single character tokens
    tokens = [w for w in tokens if len(w) > 1]
    return set(tokens)

def set_preprocess_doc(filename):
    with open(filename, 'r') as f:
        text = f.read()
    text = text.lower()
    # Perform tokenization
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    # remove punctuations but not hyphen separated words
    tokens = [w for w in tokens if w.isalpha() or '-' in w]
    # remove words with numbers
    tokens = [w for w in tokens if not any(c.isdigit() for c in w)]
    # Remove blank space tokens
    tokens = [w for w in tokens if w.strip()]
    # remove single character tokens
    tokens = [w for w in tokens if len(w) > 1]
    return set(tokens)

def preprocess_print(filename):
    # open the file and read the text
    with open(filename, 'r') as f:
        text = f.read()
    # Lowercase the text
    print()
    print("Before lower case: ",text)
    text = text.lower()
    print()
    print("After lower case: ",text)
    # Perform tokenization
    print()
    print("Before tokenization: ",text)
    tokens = word_tokenize(text)
    print()
    print("After tokenization: ",tokens)
    # Remove stopwords
    print()
    print("Before removing stopwords: ",tokens)
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    print()
    print("After removing stopwords: ",tokens)
    # remove punctuations but not hyphen separated words
    print()
    print("Before removing punctuations: ",tokens)
    tokens = [w for w in tokens if w.isalpha() or '-' in w]
    print()
    print("After removing punctuations: ",tokens)
    # Remove blank space tokens
    print()
    print("Before removing blank space tokens: ",tokens)
    tokens = [w for w in tokens if w.strip()]
    print()
    print("After removing blank space tokens: ",tokens)


for filename in tqdm(os.listdir()[0:5]):
    print(filename)
    preprocess_print(filename)
    print()

cranfield0001

Before lower case:  experimental investigation of the aerodynamics of a
wing in a slipstream .   an experimental study of a wing in a propeller slipstream was
made in order to determine the spanwise distribution of the lift
increase due to slipstream at different angles of attack of the wing
and at different free stream to slipstream velocity ratios .  the
results were intended in part as an evaluation basis for different
theoretical treatments of this problem .
  the comparative span loading curves, together with supporting
evidence, showed that a substantial part of the lift increment
produced by the slipstream was due to a /destalling/ or boundary-layer-control
effect .  the integrated remaining lift increment,
after subtracting this destalling lift, was found to agree
well with a potential flow theory .
  an empirical evaluation of the destalling effects was made for
the specific configuration of the experiment .

After lower case:  experimental investigation of the 

In [7]:
#To compute the Term Frequency, the frequency count of each term in every document is computed and stored as a nested dictionary for each document.
#The outer dictionary is indexed by the document name and the inner dictionary is indexed by the term.
#The value of the inner dictionary is the frequency count of the term in the document.
def create_tf_dict():
    tf_dict = {}
    for filename in tqdm(os.listdir()):
        tf_dict[filename] = {}
        tokens = preprocess(filename)
        for token in tokens:
            if token in tf_dict[filename]:
                tf_dict[filename][token] += 1
            else:
                tf_dict[filename][token] = 1
    return tf_dict

tf_dict = create_tf_dict()
os.chdir('../')
# store tf_dict in a json for visiualization
with open('tf_dict.json', 'w') as f:
    json.dump(tf_dict, f, indent=4)

In [8]:
# create a posting list for each term that contains the list of documents in which the term occurs, and length of the term list.
def create_posting_list():
    posting_list = {}
    for filename in tqdm(os.listdir()):
        tokens = preprocess(filename)
        for token in tokens:
            if token in posting_list:
                posting_list[token].append(filename)
            else:
                posting_list[token] = [filename]
    for token in posting_list:
        posting_list[token] = set(posting_list[token])
        posting_list[token] = [sorted(posting_list[token]), len(posting_list[token])]
    
    return posting_list

os.chdir('CSE508_Winter2023_Dataset_XML')
posting_list = create_posting_list()
# store posting_list in a json for visiualization
os.chdir('../')
with open('posting_list.json', 'w') as f:
    json.dump(posting_list, f, indent=4)

In [9]:
# create the idf for each term.
def create_idf_dict(no_of_docs):
    idf_dict = {}
    for token in posting_list:
        idf_dict[token] = math.log(no_of_docs / posting_list[token][1]+1)
    return idf_dict

idf_dict = create_idf_dict(1400)

# store idf_dict in a json for visiualization
with open('idf_dict.json', 'w') as f:
    json.dump(idf_dict, f, indent=4)

In [10]:
# create the tf-idf matrix for each document and 
# Weighting Scheme TF Weight
# Binary 0,1
# Raw count f(t,d)
# Term frequency f(t,d)/Pf(t‘, d)
# Log normalization log(1+f(t,d))
# Double normalization 0.5+0.5*(f(t,d)/ max(f(t‘,d))

def create_tf_idf_matrix_binary(no_of_docs, tf_dict, idf_dict):
    vocab_size = len(idf_dict)
    tf_idf_matrix = np.zeros((no_of_docs, vocab_size))
    # check for all terms in the idf_dict, if it is present in the tf_dict of the document, then set the value to 1*idf
    for i, filename in enumerate(tqdm(os.listdir())):
        for j, token in enumerate(idf_dict):
            if token in tf_dict[filename]:
                tf_idf_matrix[i][j] = 1*idf_dict[token]
                
    return tf_idf_matrix

def create_tf_idf_matrix_raw_count(no_of_docs, tf_dict, idf_dict):
    vocab_size = len(idf_dict)
    tf_idf_matrix = np.zeros((no_of_docs, vocab_size))
    for i, filename in enumerate(tqdm(os.listdir())):
        for j, token in enumerate(idf_dict):
            if token in tf_dict[filename]:
                tf_idf_matrix[i][j] = tf_dict[filename][token]*idf_dict[token]
                
    return tf_idf_matrix

def create_tf_idf_matrix_term_frequency(no_of_docs, tf_dict, idf_dict):
    vocab_size = len(idf_dict)
    tf_idf_matrix = np.zeros((no_of_docs, vocab_size))
    for i, filename in enumerate(tqdm(os.listdir())):
        for j, token in enumerate(idf_dict):
            if token in tf_dict[filename]:
                tf_idf_matrix[i][j] = (tf_dict[filename][token]/len(tf_dict[filename]))*idf_dict[token]

    return tf_idf_matrix

def create_tf_idf_matrix_log_normalization(no_of_docs, tf_dict, idf_dict):
    vocab_size = len(idf_dict)
    tf_idf_matrix = np.zeros((no_of_docs, vocab_size))
    for i, filename in enumerate(tqdm(os.listdir())):
        for j, token in enumerate(idf_dict):
            if token in tf_dict[filename]:
                tf_idf_matrix[i][j] = math.log(1+tf_dict[filename][token])*idf_dict[token]
    
    return tf_idf_matrix

def create_tf_idf_matrix_double_normalization(no_of_docs, tf_dict, idf_dict):
    vocab_size = len(idf_dict)
    tf_idf_matrix = np.zeros((no_of_docs, vocab_size))
    for i, filename in enumerate(tqdm(os.listdir())):
        max_tf = 0
        for token in tf_dict[filename]:
            if tf_dict[filename][token] > max_tf:
                max_tf = tf_dict[filename][token]
        for j, token in enumerate(idf_dict):
            if token in tf_dict[filename]:
                tf_idf_matrix[i][j] = 0.5+0.5*(tf_dict[filename][token]/max_tf)*idf_dict[token]
    return tf_idf_matrix

In [11]:
os.chdir('CSE508_Winter2023_Dataset_XML')
binary_tf_idf_matrix = create_tf_idf_matrix_binary(1400, tf_dict, idf_dict)
raw_count_tf_idf_matrix = create_tf_idf_matrix_raw_count(1400, tf_dict, idf_dict)
term_frequency_tf_idf_matrix = create_tf_idf_matrix_term_frequency(1400, tf_dict, idf_dict)
log_normalization_tf_idf_matrix = create_tf_idf_matrix_log_normalization(1400, tf_dict, idf_dict)
double_normalization_tf_idf_matrix = create_tf_idf_matrix_double_normalization(1400, tf_dict, idf_dict)
os.chdir('../')

In [12]:
# calculate the score of each document for a given query using the cosine similarity.
# we know that the quuerie is a vector of size vocab_size and the tf_idf_matrix is a matrix of size (no_of_docs, vocab_size)
def calculate_score(query, tf_idf_matrix, idf_dict):
    vocab_size = len(idf_dict)
    query_vector = np.zeros(vocab_size)
    # get index of the token in the idf_dict and make corresponding index in query_vector 1.
    lst_tokens = list(idf_dict.keys())
    for token in query:
        index = lst_tokens.index(token)
        query_vector[index] = 1
    scores = np.dot(tf_idf_matrix, query_vector)
    return scores

# run for every query and return the top 10 documents for each query.
def run_query(query, tf_idf_matrix, idf_dict):
    scores = calculate_score(query, tf_idf_matrix, idf_dict)
    top_10 = np.argsort(scores)[::-1][:10]
    return top_10+1

In [13]:
os.chdir('CSE508_Winter2023_Dataset_XML')
query = preprocess('cranfield0001')
print(run_query(query,binary_tf_idf_matrix, idf_dict))
print(run_query(query,raw_count_tf_idf_matrix, idf_dict))
print(run_query(query,term_frequency_tf_idf_matrix, idf_dict))
print(run_query(query,log_normalization_tf_idf_matrix, idf_dict))
print(run_query(query,double_normalization_tf_idf_matrix, idf_dict))

[   1  484  453  601  927 1164 1064  225  173 1092]
[   1  484 1064 1092  453  673  696  695   42 1239]
[   1  484 1064  453  696  197  920 1094 1164 1075]
[   1  484 1064  453 1092 1164  927  225  695  197]
[   1 1064  601 1092  484  453  556 1218  572 1164]


In [20]:
#Jaccard Similarity
def jaccard_similarity(query, document):
    intersection = len(set(query).intersection(set(document)))
    union = len(set(query).union(set(document)))
    return intersection/union

# calculate the score of each document for a given query using the jaccard similarity.
# we know that the quuerie is a vector of size vocab_size and the tf_idf_matrix is a matrix of size (no_of_docs, vocab_size)
def calculate_score_jaccard(query):
    score = []
    query = set_preprocess_query(query)
    for filename in tqdm(os.listdir()):
        document = set_preprocess_doc(filename)
        jaccard_similarity(query, document)
        score.append(jaccard_similarity(query, document))
    return score

def get_top_10_jaccard(query):
    scores = calculate_score_jaccard(query)
    top_10 = np.argsort(scores)[::-1][:10]
    return top_10+1

query = '''experimental investigation of the aerodynamics of a
wing in a slipstream .   an experimental study of a wing in a propeller slipstream was
made in order to determine the spanwise distribution of the lift
increase due to slipstream at different angles of attack of the wing
and at different free stream to slipstream velocity ratios .  the
results were intended in part as an evaluation basis for different
theoretical treatments of this problem .
  the comparative span loading curves, together with supporting
evidence, showed that a substantial part of the lift increment
produced by the slipstream was due to a /destalling/ or boundary-layer-control
effect .  the integrated remaining lift increment,
after subtracting this destalling lift, was found to agree
well with a potential flow theory .
  an empirical evaluation of the destalling effects was made for
the specific configuration of the experiment .'''
top10 = get_top_10_jaccard(query)
print(top10)


[   1  197  601 1075  918  484  556  920 1164  901]
